### ISSUE TITLE
WM8741 Board

### ISSUE THREAD

**Issue by spaceman5** [sosandroid/WM8741-Arduino#1]
Hi sosandroid

Thank you very much for creating the WM8741-Arduino library.

May I please ask you what WM8741 Board are you using, and where you bought it?
Or is it one that you prepared?

Thank you

**Comment by sosandroid** [comment]
Hi,  This is a Twisted Pear Audio board. Link at th beginning of the Readme.md file

**Comment by spaceman5** [comment]
Thank you sosandroid.
